server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据库操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.rongda.springcloud.entities    # 所有Entity别名类所在包

