server:
  port: 80  #80表示注册到zookeeper服务器的订单服务提供者端口号

spring:
  application:
    name: cloud-consumer-order #服务别名 -- 注册zookeeper到注册中心名称
  cloud:
    zookeeper:
      connect-string: 192.168.25.164:2181 #注册到zookeeper地址