server:
  port: 80

eureka:
  client:
    register-with-eureka: false #表示是否将自己注册进EurekaServer 默认为true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      defaultZone: http://eureka7001.com:7001/eureka #单机版

# 用于服务降级 在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix